# Generated by Django 3.2.8 on 2021-12-21 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modoPacienteObligado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abonado', models.BooleanField(default=False)),
                ('fechaAlta', models.DateField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fechaFin', models.DateField(null=True)),
                ('retrasado', models.BooleanField(default=False)),
                ('empleadoCarga', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.empleado')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='En procesamiento', max_length=50)),
                ('urlResultado', models.CharField(default='Sin cargar', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicoDerivante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('matricula', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicoInformante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nombreTutor', models.CharField(max_length=100, null=True)),
                ('apellidoTutor', models.CharField(max_length=100, null=True)),
                ('dni', models.BigIntegerField(unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('numeroAfiliado', models.BigIntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('new', models.BooleanField(default=True)),
                ('obraSocial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.obrasocial')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaAlta', models.DateField()),
                ('fechaRetiro', models.DateField(null=True)),
                ('numeroFreezer', models.BigIntegerField()),
                ('mlExtraidos', models.DecimalField(decimal_places=1, max_digits=3)),
                ('personaRetira', models.CharField(max_length=100, null=True)),
                ('error', models.BooleanField(default=False)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estudio')),
                ('lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.FloatField()),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estudio')),
            ],
        ),
        migrations.AddField(
            model_name='estudio',
            name='medicoDerivante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.medicoderivante'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.paciente'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='patologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.patologia'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='tipoEstudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.tipoestudio'),
        ),
        migrations.CreateModel(
            name='ConsentimientoFirmado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(max_length=1000, upload_to='consentimientosFirmados/')),
                ('url', models.CharField(max_length=1000)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(max_length=1000, upload_to='consentimientos/')),
                ('url', models.CharField(max_length=1000)),
                ('tipoEstudio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.tipoestudio')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(max_length=1000, upload_to='comprobantes/')),
                ('url', models.CharField(max_length=1000)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Interpretacion',
            fields=[
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.estudio')),
                ('resultado', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('informe', models.CharField(max_length=10000)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.medicoinformante')),
            ],
        ),
    ]
