# Generated by Django 3.2.8 on 2021-10-16 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoEstudio', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=100)),
                ('fechaAlta', models.DateField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diagnosticoPresuntivo', models.TextField(max_length=400)),
                ('empleadoCarga', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicoDerivante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('matricula', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('resumenHClinica', models.TextField(max_length=100)),
                ('numeroAfiliado', models.IntegerField()),
                ('obraSocial', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.obrasocial')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('numeroFreezer', models.IntegerField()),
                ('personaRetira', models.CharField(max_length=100)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.lote')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField()),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.estudio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='estudio',
            name='medicoDerivante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.medicoderivante'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.paciente'),
        ),
    ]
