# Generated by Django 3.2.8 on 2021-12-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='consentimiento',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='consentimientofirmado',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
