# Generated by Django 3.2.8 on 2021-11-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='obraSocial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.obrasocial'),
        ),
    ]
