# Generated by Django 3.2.8 on 2021-12-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='urlResultado',
            field=models.CharField(default='Sin cargar', max_length=100),
        ),
    ]
