# Generated by Django 3.2.8 on 2021-11-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='paciente',
        ),
    ]
