# Generated by Django 3.2.8 on 2021-12-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_lote_urlresultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
